import { expect, test, type APIRequestContext, type Page } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";

test.skip(!process.env.PHASE2_E2E,"Requires the explicit disposable PostgreSQL staging path.");
test.beforeEach(async({},testInfo)=>{test.skip(testInfo.project.name!=="1920x1080","Correction-path concurrency runs once; frozen and A-H coverage still run at all three viewports.");});

const actor="development-employee";
const api="http://127.0.0.1:4174/api";
const headers={"x-development-user":actor};

async function importBatch(request:APIRequestContext,label:string){const content=await readFile(new URL("../../../fixtures/phase2-controlled-eight-scenarios-v1.csv",import.meta.url),"utf8");const response=await request.post(`${api}/batches/import`,{headers,data:{importKey:`correction-${label}-${randomUUID()}`,filename:"correction.csv",mimeType:"text/csv",content,name:`Correction ${label}`}});expect(response.status()).toBe(201);return await response.json() as {batchId:string};}
async function openBatch(page:Page,batchId:string){await page.goto(`/employee?batchId=${batchId}`);await expect(page.getByText("SKU: VTK-00623",{exact:true})).toBeVisible();}
async function makeAnswerReady(page:Page,condition="A"){await page.getByRole("button",{name:"NONE OF THESE ARE INCLUDED"}).click();await page.getByTestId(`btn-condition-${condition}`).click();await expect(page.getByTestId("btn-save-next")).toBeEnabled();}

test("Needs Review response loss replays one committed review with the same logical operation",async({page,request})=>{const {pool}=await import("@workspace/db");const {batchId}=await importBatch(request,"review-loss");await openBatch(page,batchId);await page.evaluate(()=>localStorage.setItem("vtk-drop-next-response","review"));await page.getByRole("button",{name:/NEEDS REVIEW/}).click();await expect(page.getByRole("alert")).toBeVisible();await page.getByRole("button",{name:/NEEDS REVIEW/}).click();await expect(page.getByText("Item 2 of 8")).toBeVisible({timeout:10000});const items=await pool.query<{id:string;status:string;version:number}>("select id,status,version from listing_items where batch_id=$1 order by source_row_number",[batchId]);expect(items.rows[0]).toMatchObject({status:"needs_review",version:2});expect((await pool.query("select 1 from review_records where item_id=$1",[items.rows[0].id])).rowCount).toBe(1);expect((await pool.query("select 1 from audit_events where item_id=$1 and action='needs_review_selected'",[items.rows[0].id])).rowCount).toBe(1);expect((await pool.query("select 1 from idempotency_records where actor_id=$1 and response_body->>'itemId'=$2",[actor,items.rows[0].id])).rowCount).toBe(1);const progress=await request.get(`${api}/batches/${batchId}/progress`,{headers});expect(await progress.json()).toMatchObject({reviewCount:1,processedCount:1,pendingCount:7,complete:false});expect((await pool.query("select 1 from audit_events where batch_id=$1 and action='batch_completed'",[batchId])).rowCount).toBe(0);});

test("post-commit progress failures reconcile answer and review, release locks, and reload authoritatively",async({page,request})=>{const {pool}=await import("@workspace/db");for(const mode of ["answer","review"] as const){const {batchId}=await importBatch(request,`progress-${mode}`);await openBatch(page,batchId);if(mode==="answer")await makeAnswerReady(page);await page.evaluate(()=>localStorage.setItem("vtk-fail-next-progress","true"));if(mode==="answer")await page.getByTestId("btn-save-next").click();else await page.getByRole("button",{name:/NEEDS REVIEW/}).click();await expect(page.getByRole("alert")).toContainText(mode==="answer"?"Item saved. Progress could not refresh":"Review saved. Progress could not refresh");await expect(page.getByText("Item 2 of 8")).toBeVisible({timeout:5000});await page.reload();await expect(page.getByText("SKU: VTK-00623",{exact:true})).toBeVisible();const item=await pool.query<{id:string;status:string;version:number}>("select id,status,version from listing_items where batch_id=$1 order by source_row_number limit 1",[batchId]);expect(item.rows[0]).toMatchObject({status:mode==="answer"?"completed":"needs_review",version:2});expect((await pool.query("select 1 from audit_events where item_id=$1 and action=$2",[item.rows[0].id,mode==="answer"?"employee_answer_saved":"needs_review_selected"])).rowCount).toBe(1);expect((await pool.query("select 1 from review_records where item_id=$1",[item.rows[0].id])).rowCount).toBe(mode==="review"?1:0);const progress=await request.get(`${api}/batches/${batchId}/progress`,{headers});expect(await progress.json()).toMatchObject({processedCount:1,pendingCount:7,completedCount:mode==="answer"?1:0,reviewCount:mode==="review"?1:0});}}
);

test("two tabs reject stale draft version without overwriting the authoritative draft",async({page,context,request})=>{const {pool}=await import("@workspace/db");const {batchId}=await importBatch(request,"two-tab");const stale=await context.newPage();await Promise.all([openBatch(page,batchId),openBatch(stale,batchId)]);await makeAnswerReady(page,"A");await page.waitForTimeout(800);const staleResponse=stale.waitForResponse((response)=>response.url().includes("/draft")&&response.status()===409);await makeAnswerReady(stale,"B");const response=await staleResponse;const body=await response.json() as {currentDraftVersion:number};expect(body.currentDraftVersion).toBe(1);await expect(stale.getByRole("alert")).toContainText("draft changed");const item=await pool.query<{id:string}>("select id from listing_items where batch_id=$1 order by source_row_number limit 1",[batchId]);const saved=await pool.query<{version:number;answer:Record<string,unknown>}>("select version,answer from item_drafts where item_id=$1 and employee_id=$2",[item.rows[0].id,actor]);expect(saved.rows[0].version).toBe(1);expect(saved.rows[0].answer.conditionCode).toBe("A");expect((await pool.query("select 1 from audit_events where item_id=$1 and action='item_draft_saved'",[item.rows[0].id])).rowCount).toBe(1);await stale.close();});

test("delayed autosave orders navigation and required draft failure cannot silently navigate",async({page,request})=>{const {pool}=await import("@workspace/db");const delayed=await importBatch(request,"navigation-delay");await openBatch(page,delayed.batchId);await page.evaluate(()=>localStorage.setItem("vtk-delay-next-draft","true"));await makeAnswerReady(page,"A");await page.waitForTimeout(650);await page.getByTestId("btn-next-item").click();await expect(page.getByText("Item 2 of 8")).toBeVisible({timeout:5000});const delayedItem=await pool.query<{id:string}>("select id from listing_items where batch_id=$1 order by source_row_number limit 1",[delayed.batchId]);const draft=await pool.query<{version:number;answer:Record<string,unknown>}>("select version,answer from item_drafts where item_id=$1",[delayedItem.rows[0].id]);expect(draft.rows[0].version).toBe(2);expect(draft.rows[0].answer.conditionCode).toBe("A");expect((await pool.query("select 1 from audit_events where item_id=$1 and action='item_draft_saved'",[delayedItem.rows[0].id])).rowCount).toBe(2);
  const failed=await importBatch(request,"navigation-failure");await openBatch(page,failed.batchId);await page.evaluate(()=>localStorage.setItem("vtk-fail-next-draft","true"));await makeAnswerReady(page,"B");await page.getByTestId("btn-next-item").click();await expect(page.getByText("Item 1 of 8")).toBeVisible();await expect(page.getByRole("alert")).toContainText("Draft not saved");const failedItem=await pool.query<{id:string}>("select id from listing_items where batch_id=$1 order by source_row_number limit 1",[failed.batchId]);expect((await pool.query("select 1 from item_drafts where item_id=$1",[failedItem.rows[0].id])).rowCount).toBe(0);await page.getByTestId("btn-next-item").click();await expect(page.getByText("Item 2 of 8")).toBeVisible({timeout:5000});expect((await pool.query("select 1 from item_drafts where item_id=$1",[failedItem.rows[0].id])).rowCount).toBe(1);});

test("in-flight drafts finish before final answer and Needs Review without resurrection",async({page,request})=>{const {pool}=await import("@workspace/db");for(const mode of ["answer","review"] as const){const {batchId}=await importBatch(request,`draft-${mode}`);await openBatch(page,batchId);await page.evaluate(()=>localStorage.setItem("vtk-delay-next-draft","true"));await makeAnswerReady(page,mode==="answer"?"A":"B");await page.waitForTimeout(650);if(mode==="answer")await page.getByTestId("btn-save-next").click();else await page.getByRole("button",{name:/NEEDS REVIEW/}).click();await expect(page.getByText("Item 2 of 8")).toBeVisible({timeout:6000});await page.waitForTimeout(1100);const item=await pool.query<{id:string;status:string;version:number}>("select id,status,version from listing_items where batch_id=$1 order by source_row_number limit 1",[batchId]);expect(item.rows[0]).toMatchObject({status:mode==="answer"?"completed":"needs_review",version:2});const stored=await pool.query<{version:number;draft_status:string;answer:Record<string,unknown>}>("select version,draft_status,answer from item_drafts where item_id=$1 and employee_id=$2",[item.rows[0].id,actor]);expect(stored.rows[0].version).toBe(2);expect(stored.rows[0].draft_status).toBe(mode==="answer"?"submitted":"needs_review");expect(stored.rows[0].answer.conditionCode).toBe(mode==="answer"?"A":"B");expect((await pool.query("select 1 from audit_events where item_id=$1 and action='item_draft_saved'",[item.rows[0].id])).rowCount).toBe(1);expect((await pool.query("select 1 from audit_events where item_id=$1 and action=$2",[item.rows[0].id,mode==="answer"?"employee_answer_saved":"needs_review_selected"])).rowCount).toBe(1);expect((await pool.query("select 1 from review_records where item_id=$1",[item.rows[0].id])).rowCount).toBe(mode==="review"?1:0);}}
);
