import { expect,test } from "@playwright/test";
import { readFile } from "node:fs/promises";

test.skip(!process.env.PHASE2_E2E,"Requires the explicit disposable PostgreSQL staging path.");
test("imported PostgreSQL batch restores draft and completes with authoritative progress and audit",async({page,request},testInfo)=>{
  const {pool}=await import("@workspace/db");
  const content=await readFile(new URL("../../../fixtures/phase2-controlled-eight-scenarios-v1.csv",import.meta.url),"utf8");
  const imported=await request.post("http://127.0.0.1:4174/api/batches/import",{headers:{"x-development-user":"development-employee"},data:{importKey:`browser-${testInfo.project.name}`,filename:"phase2-eight.csv",mimeType:"text/csv",content,name:`Phase 2 ${testInfo.project.name}`}});expect(imported.status()).toBe(201);const {batchId}=await imported.json();
  await page.goto(`/employee?batchId=${batchId}`);await expect(page.getByText("SKU: VTK-00623",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"NONE OF THESE ARE INCLUDED"}).click();await page.getByTestId("btn-condition-A").click();await expect(page.getByTestId("btn-save-next")).toBeEnabled();await page.waitForTimeout(800);
  await page.reload();await expect(page.getByText("SKU: VTK-00623",{exact:true})).toBeVisible();await expect(page.getByTestId("btn-save-next")).toBeEnabled();
  await page.evaluate(()=>localStorage.setItem("vtk-drop-next-response","answer"));await page.getByTestId("btn-save-next").click();await expect(page.getByRole("alert")).toBeVisible();await page.getByTestId("btn-save-next").click();await expect(page.getByText("Item 2 of 8")).toBeVisible({timeout:5000});
  for(const key of ["1","2","3","4","5","6","7","8"])await page.keyboard.press(key);await page.keyboard.press("A");await page.keyboard.press("Enter");await expect(page.getByText("Item 3 of 8")).toBeVisible({timeout:5000});
  await page.getByRole("button",{name:"NONE OF THESE ARE INCLUDED"}).click();await page.keyboard.press("A");await page.keyboard.press("Enter");await expect(page.getByText("Item 4 of 8")).toBeVisible({timeout:5000});
  await page.getByRole("button",{name:"−"}).click();await page.keyboard.press("D");await expect(page.getByTestId("btn-save-next")).toBeDisabled();await page.getByRole("button",{name:"+"}).click();await page.getByTestId("btn-save-next").click();await expect(page.getByText("Item 5 of 8")).toBeVisible({timeout:5000});
  await page.keyboard.press("1");await page.keyboard.press("2");await page.keyboard.press("A");await page.keyboard.press("Enter");await expect(page.getByText("Item 6 of 8")).toBeVisible({timeout:5000});
  await page.keyboard.press("A");await expect(page.getByTestId("btn-save-next")).toBeDisabled();await page.getByRole("button",{name:"+"}).click();await page.getByTestId("btn-save-next").click();await expect(page.getByText("Item 7 of 8")).toBeVisible({timeout:5000});
  await page.keyboard.press("1");await page.keyboard.press("2");await page.keyboard.press("B");await page.getByPlaceholder("e.g. minor scratches").fill("Housing damage near feed path");await page.getByRole("button",{name:/NEEDS REVIEW/}).click();await expect(page.getByText("Item 8 of 8")).toBeVisible({timeout:5000});
  await page.keyboard.press("1");await page.keyboard.press("2");await page.keyboard.press("D");await page.keyboard.press("Enter");
  await expect(page.getByRole("heading",{name:"Batch Complete"})).toBeVisible({timeout:5000});await page.reload();await expect(page.getByRole("heading",{name:"Batch Complete"})).toBeVisible();
  const progress=await request.get(`http://127.0.0.1:4174/api/batches/${batchId}/progress`,{headers:{"x-development-user":"development-employee"}});expect(await progress.json()).toMatchObject({totalItemCount:8,completedCount:7,reviewCount:1,processedCount:8,pendingCount:0,percent:100,complete:true});
  const state=await pool.query<{status:string}>("select status from batches where id=$1",[batchId]);expect(state.rows[0].status).toBe("completed");
  const items=await pool.query<{source_row_id:string;status:string;version:number;answer:Record<string,unknown>}>("select li.source_row_id,li.status,li.version,d.answer from listing_items li join item_drafts d on d.item_id=li.id and d.employee_id='development-employee' where li.batch_id=$1 order by li.source_row_number",[batchId]);expect(items.rows.map((row)=>[row.source_row_id,row.status,row.version])).toEqual([["A","completed",2],["B","completed",2],["C","completed",2],["D","completed",2],["E","completed",2],["F","completed",2],["G","needs_review",2],["H","completed",2]]);expect((items.rows[1].answer.includedItems as {selectedQuestionIds:string[]}).selectedQuestionIds).toHaveLength(8);expect((items.rows[3].answer.fieldValues as Record<string,unknown>).qtyToList).toBe(1);expect((items.rows[4].answer.fieldValues as Record<string,unknown>).checkCount).toBe(true);expect((items.rows[5].answer.fieldValues as Record<string,unknown>).qtyToList).toBe(1);expect((items.rows[6].answer.fieldValues as Record<string,unknown>).otherNotes).toBe("Housing damage near feed path");expect(items.rows[7].answer.conditionCode).toBe("D");
  const review=await pool.query<{note:string;entered_answer:Record<string,unknown>}>("select note,entered_answer from review_records rr join listing_items li on li.id=rr.item_id where li.batch_id=$1",[batchId]);expect(review.rowCount).toBe(1);expect(review.rows[0].note).toBe("Employee requested review.");
  const audit=await pool.query<{action:string;count:string}>("select action,count(*)::text as count from audit_events where batch_id=$1 group by action",[batchId]);const counts=Object.fromEntries(audit.rows.map((row)=>[row.action,Number(row.count)]));expect(counts).toMatchObject({batch_import_created:1,employee_answer_saved:7,needs_review_selected:1,batch_completed:1});
});
