import assert from "node:assert/strict";
import test from "node:test";
import { mkdir, mkdtemp, readFile, readdir, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve, sep } from "node:path";
import { NonproductionFilesystemStorage } from "./file-storage";

test("filesystem storage uses generated contained keys, removes exactly its file, and is production-forbidden",async()=>{const root=await mkdtemp(join(tmpdir(),"vtk-storage-"));const old={node:process.env.NODE_ENV,app:process.env.APP_ENV,allow:process.env.ALLOW_NONPRODUCTION_STORAGE};try{process.env.NODE_ENV="test";process.env.APP_ENV="staging";process.env.ALLOW_NONPRODUCTION_STORAGE="true";const storage=new NonproductionFilesystemStorage(root);const stored=await storage.store(Buffer.from("safe"));assert.match(stored.key,/^[0-9a-f-]{36}\.csv$/);const target=resolve(root,stored.key);assert.ok(target.startsWith(`${resolve(root)}${sep}`));assert.equal(await readFile(target,"utf8"),"safe");await stored.remove();await assert.rejects(()=>readFile(target));process.env.APP_ENV="production";assert.throws(()=>new NonproductionFilesystemStorage(root),/forbidden/);}finally{for(const [key,value] of Object.entries(old)){if(value===undefined)delete process.env[key.toUpperCase()==="NODE"?"NODE_ENV":key.toUpperCase()==="APP"?"APP_ENV":"ALLOW_NONPRODUCTION_STORAGE"];else if(key==="node")process.env.NODE_ENV=value;else if(key==="app")process.env.APP_ENV=value;else process.env.ALLOW_NONPRODUCTION_STORAGE=value;}await rm(root,{recursive:true,force:true});}});

test("filesystem storage rejects symlink roots and nested symlink components",async()=>{const sandbox=await mkdtemp(join(tmpdir(),"vtk-storage-links-"));const outside=join(sandbox,"outside");const rootLink=join(sandbox,"root-link");const nestedParent=join(sandbox,"nested");const nestedLink=join(nestedParent,"redirect");const old={node:process.env.NODE_ENV,app:process.env.APP_ENV,allow:process.env.ALLOW_NONPRODUCTION_STORAGE};try{process.env.NODE_ENV="test";process.env.APP_ENV="staging";process.env.ALLOW_NONPRODUCTION_STORAGE="true";await mkdir(outside);await mkdir(nestedParent);await symlink(outside,rootLink,process.platform==="win32"?"junction":"dir");await symlink(outside,nestedLink,process.platform==="win32"?"junction":"dir");await assert.rejects(()=>new NonproductionFilesystemStorage(rootLink).store(Buffer.from("escape")),/symbolic link|reparse-point/);await assert.rejects(()=>new NonproductionFilesystemStorage(join(nestedLink,"child")).store(Buffer.from("escape")),/symbolic link|reparse-point/);assert.deepEqual(await readdir(outside),[]);}finally{if(old.node===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=old.node;if(old.app===undefined)delete process.env.APP_ENV;else process.env.APP_ENV=old.app;if(old.allow===undefined)delete process.env.ALLOW_NONPRODUCTION_STORAGE;else process.env.ALLOW_NONPRODUCTION_STORAGE=old.allow;await rm(sandbox,{recursive:true,force:true});}});

test("filesystem removal refuses a redirected target and never deletes external content",async()=>{const sandbox=await mkdtemp(join(tmpdir(),"vtk-storage-remove-"));const root=join(sandbox,"root");const external=join(sandbox,"external");const marker=join(external,"marker.txt");const old={node:process.env.NODE_ENV,app:process.env.APP_ENV,allow:process.env.ALLOW_NONPRODUCTION_STORAGE};try{process.env.NODE_ENV="test";process.env.APP_ENV="staging";process.env.ALLOW_NONPRODUCTION_STORAGE="true";const storage=new NonproductionFilesystemStorage(root);const stored=await storage.store(Buffer.from("safe"));await mkdir(external);await writeFile(marker,"external");await rm(join(root,stored.key));await symlink(external,join(root,stored.key),process.platform==="win32"?"junction":"dir");await assert.rejects(()=>stored.remove(),/removal escaped/);assert.equal(await readFile(marker,"utf8"),"external");}finally{if(old.node===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=old.node;if(old.app===undefined)delete process.env.APP_ENV;else process.env.APP_ENV=old.app;if(old.allow===undefined)delete process.env.ALLOW_NONPRODUCTION_STORAGE;else process.env.ALLOW_NONPRODUCTION_STORAGE=old.allow;await rm(sandbox,{recursive:true,force:true});}});
