import { randomUUID } from "node:crypto";
import { and, asc, eq, inArray, sql } from "drizzle-orm";
import { db, auditEvents, batches, importedFiles, itemDrafts, listingItems } from "@workspace/db";
import { ApiFault } from "../lib/errors";
import { CONTROLLED_SCHEMA_VERSION, parseControlledCsv, safeFilename } from "./controlled-csv";
import type { FileStorage } from "./file-storage";

const pendingStatuses = ["pending", "ready_for_employee", "in_progress"] as const;
function progress(statuses: string[]) { const completedCount = statuses.filter((s) => ["completed", "reviewed", "exported"].includes(s)).length; const reviewCount = statuses.filter((s) => s === "needs_review").length; const processedCount = completedCount + reviewCount; return { totalItemCount: statuses.length, completedCount, reviewCount, processedCount, pendingCount: statuses.length - processedCount, percent: statuses.length ? Math.round(processedCount / statuses.length * 100) : 0, complete: statuses.length > 0 && processedCount === statuses.length }; }

export class Phase2Service {
  constructor(private readonly storage: FileStorage) {}
  async importBatch(input: { actorId: string; role: string; importKey: string; filename: string; mimeType: string; content: string; name?: string; correlationId: string }) {
    if (!input.importKey || input.importKey.length > 200) throw new ApiFault(400, "VALIDATION_ERROR", "A valid importKey is required.");
    const parsed = parseControlledCsv(input); const prior = await db.select().from(batches).where(and(eq(batches.createdBy, input.actorId), eq(batches.importKey, input.importKey))).limit(1);
    if (prior[0]) { if (prior[0].sourceChecksum !== parsed.checksum) throw new ApiFault(409, "CONFLICT", "The import key was already used for different content."); return { batchId: prior[0].id, replayed: true, itemCount: parsed.rows.length, checksum: parsed.checksum }; }
    const stored = await this.storage.store(parsed.bytes);
    try {
      return await db.transaction(async (tx) => {
        await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${`${input.actorId}:batch_import:${input.importKey}`}))`);
        const raced = await tx.select().from(batches).where(and(eq(batches.createdBy, input.actorId), eq(batches.importKey, input.importKey))).limit(1);
        if (raced[0]) { if (raced[0].sourceChecksum !== parsed.checksum) throw new ApiFault(409, "CONFLICT", "The import key was already used for different content."); await stored.remove(); return { batchId: raced[0].id, replayed: true, itemCount: parsed.rows.length, checksum: parsed.checksum }; }
        const [batch] = await tx.insert(batches).values({ name: input.name?.trim() || safeFilename(input.filename), source: "csv", status: "ready_for_employee", createdBy: input.actorId, importKey: input.importKey, sourceChecksum: parsed.checksum, schemaVersion: CONTROLLED_SCHEMA_VERSION, sourceFileMetadata: { originalFilename: input.filename, safeFilename: safeFilename(input.filename), mimeType: input.mimeType, sizeBytes: parsed.bytes.length, checksum: parsed.checksum, storageKey: stored.key } }).returning();
        await tx.insert(listingItems).values(parsed.rows.map((row) => ({ batchId: batch.id, sourceRowId: row.original.scenario, sourceRowNumber: row.rowNumber, sku: row.original.sku, inventoryId: null, itemId: null, originalValues: row.original, normalizedValues: row.normalized, questionConfiguration: row.questions, warnings: row.original.warning ? [row.original.warning] : [], status: "ready_for_employee" as const })));
        await tx.insert(importedFiles).values({ batchId: batch.id, uploaderId: input.actorId, originalFilename: input.filename, safeFilename: safeFilename(input.filename), mimeType: input.mimeType, checksum: parsed.checksum, sizeBytes: parsed.bytes.length, storageKey: stored.key, status: "imported" });
        await tx.insert(auditEvents).values({ batchId: batch.id, actorId: input.actorId, actorRole: input.role as "employee" | "reviewer" | "admin", action: "batch_import_created", correlationId: input.correlationId, newStatus: "ready_for_employee", metadata: { checksum: parsed.checksum, rowCount: parsed.rows.length, schemaVersion: CONTROLLED_SCHEMA_VERSION } });
        return { batchId: batch.id, replayed: false, itemCount: parsed.rows.length, checksum: parsed.checksum };
      });
    } catch (error) { await stored.remove(); throw error; }
  }
  async listBatches() { const rows = await db.select().from(batches).orderBy(asc(batches.createdAt)); return Promise.all(rows.map(async (batch) => ({ ...batch, progress: await this.getProgress(batch.id) }))); }
  async getBatch(batchId: string) { const [batch] = await db.select().from(batches).where(eq(batches.id, batchId)).limit(1); if (!batch) throw new ApiFault(404, "NOT_FOUND", "Batch was not found."); return { ...batch, progress: await this.getProgress(batchId) }; }
  async getProgress(batchId: string) { const rows = await db.select({ status: listingItems.status }).from(listingItems).where(eq(listingItems.batchId, batchId)); if (!rows.length) { const exists = await db.select({id:batches.id}).from(batches).where(eq(batches.id,batchId)).limit(1); if (!exists[0]) throw new ApiFault(404,"NOT_FOUND","Batch was not found."); } return progress(rows.map((row) => row.status)); }
  async listItems(batchId: string, actorId: string) { await this.getBatch(batchId); const rows = await db.select().from(listingItems).where(eq(listingItems.batchId, batchId)).orderBy(asc(listingItems.sourceRowNumber), asc(listingItems.id)); const drafts = await db.select().from(itemDrafts).where(and(eq(itemDrafts.employeeId, actorId), inArray(itemDrafts.itemId, rows.map((row) => row.id)))); const byItem = new Map(drafts.map((draft) => [draft.itemId, draft])); return rows.map((row) => ({ ...row, draft: byItem.get(row.id)?.answer ?? null })); }
  async getItem(itemId: string, actorId: string) { const [row] = await db.select().from(listingItems).where(eq(listingItems.id, itemId)).limit(1); if (!row) throw new ApiFault(404,"NOT_FOUND","Listing item was not found."); const [draft] = await db.select().from(itemDrafts).where(and(eq(itemDrafts.itemId,itemId),eq(itemDrafts.employeeId,actorId))).limit(1); return { ...row, draft: draft?.answer ?? null }; }
  async nextItem(batchId: string, actorId: string) { const [row] = await db.select().from(listingItems).where(and(eq(listingItems.batchId,batchId),inArray(listingItems.status,[...pendingStatuses]))).orderBy(asc(listingItems.sourceRowNumber),asc(listingItems.id)).limit(1); return row ? this.getItem(row.id, actorId) : null; }
  async saveDraft(itemId: string, actorId: string, draft: Record<string, unknown>, correlationId: string) {
    if (draft.employeeId !== actorId) throw new ApiFault(403,"FORBIDDEN","Draft employee identity does not match the authenticated identity.");
    return db.transaction(async (tx) => { const [item] = await tx.select().from(listingItems).where(eq(listingItems.id,itemId)).for("update").limit(1); if (!item) throw new ApiFault(404,"NOT_FOUND","Listing item was not found."); if (draft.itemId !== itemId) throw new ApiFault(400,"VALIDATION_ERROR","Route item ID does not match draft item ID."); if (draft.itemVersion !== item.version) throw new ApiFault(409,"CONFLICT","The listing item changed after this draft was loaded.",{currentVersion:item.version}); if (!pendingStatuses.includes(item.status as typeof pendingStatuses[number])) throw new ApiFault(409,"CONFLICT","A final item cannot accept a draft.",{currentVersion:item.version}); const answer={...draft,status:"editing",updatedAt:new Date().toISOString()}; const [saved]=await tx.insert(itemDrafts).values({itemId,employeeId:actorId,itemVersion:item.version,draftStatus:"editing",answer}).onConflictDoUpdate({target:[itemDrafts.itemId,itemDrafts.employeeId],set:{itemVersion:item.version,draftStatus:"editing",answer,version:sql`${itemDrafts.version}+1`,updatedAt:new Date()}}).returning(); if(item.status==="ready_for_employee") await tx.update(listingItems).set({status:"in_progress",updatedAt:new Date()}).where(eq(listingItems.id,itemId)); await tx.insert(auditEvents).values({itemId,batchId:item.batchId,actorId,actorRole:"employee",action:"item_draft_saved",previousStatus:item.status,newStatus:item.status==="ready_for_employee"?"in_progress":item.status,correlationId,metadata:{draftVersion:saved.version}}); return {itemId,itemVersion:item.version,draftVersion:saved.version,status:"editing"}; });
  }
}
